# Stock Analytics

This notebook explores the unified ETL (Extract, Transform, Load) Pipeline for stock data.

**Version:** 1.2.0 | **Model Version:** v9_10 | **Updated:** 2025-12-18

## Pipeline Stages
1. **Extract** - Load from DB with CSV fallback
2. **Transform** - Normalize, validate, sanitize, impute (6-step)
3. **Load** - Quality validation and finalization

## 17 Feature Categories (229 Features)
- Momentum & Technical, Valuation Ratios, Profitability, Quality & Risk
- Cash Flow, Capital Allocation, Analyst Sentiment, Market Sentiment
- Leverage & Liquidity, Temporal Patterns, Composite Scores, Growth Metrics
- Efficiency Ratios, Employee Productivity, Balance Sheet, Revenue Forecasting
- **NEW: Earnings Quality** (33 features for EPS/revenue surprise, GAAP vs. Adjusted metrics)

## Feature Engineering API (`build_features`)

**Business Goal:** Engineer comprehensive financial features including valuation ratios,
profitability metrics, quality indicators, and sector-specific features to maximize model predictive power.

**Key Objectives:**
- Engineer valuation ratios (P/E, P/B, EV/EBITDA, PEG)
- Engineer profitability features (margins, ROE, ROA, ROIC)
- Create momentum and technical indicators
- Engineer analyst quality features
- Create accounting quality scores (Altman Z, Piotroski F)
- Build sector-relative features
- Create interaction features

## Refactoring Improvements (v1.1.0)

**Schema Integration (`finance_ml.ml_workflow.data.schema`):**
- Centralized column definitions via `COLUMN_SCHEMA` (318 columns)
- Schema-driven column selection using helper functions
- Phase 9.3 feature categorization via `PHASE93_FEATURE_CATEGORIES`

**Code Guidelines Alignment (`code_guidelines.md` Section 8):**
- Configuration constants (Section 8.1): Single source of truth for all parameters
- Replaced hard-coded magic numbers with named constants
- Schema-driven numeric/categorical/date column selection

**Benefits:**
- Eliminates schema drift between notebook and canonical definitions
- Reduces maintenance burden from hard-coded column lists
- Ensures consistency with ETL pipeline and feature engineering modules
- Aligns with project-wide code quality standards

In [1]:
# ============================================================================
# Cell 1: Configuration & Setup
# ============================================================================
import json
import os
import sys
import warnings
from pathlib import Path

warnings.filterwarnings('ignore')

import pandas as pd
import numpy as np

# NumPy compatibility note:
# Avoid modifying NumPy private attributes to satisfy PyDeprecationInspection and stability concerns.
# If certain libraries expect np._ARRAY_API, prefer updating those libraries rather than mutating NumPy.
# Here, we intentionally do NOT set any private compatibility shims.

import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

# SQLAlchemy check
try:
    from sqlalchemy import create_engine, text

    HAVE_SQLALCHEMY = True
except ImportError:
    HAVE_SQLALCHEMY = False

# Project paths
PROJECT_ROOT = Path.cwd()
DATA_DIR = PROJECT_ROOT / 'data'
OUTPUT_DIR = PROJECT_ROOT / 'outputs'
CACHE_DIR = PROJECT_ROOT / '.cache'

try:
    (OUTPUT_DIR / 'eda').mkdir(parents=True, exist_ok=True)
    (OUTPUT_DIR / 'preprocessing').mkdir(parents=True, exist_ok=True)
except Exception as dir_err:
    # Graceful handling for permission/disk issues without crashing the notebook
    print(f"Warning: could not ensure output directories exist: {dir_err}")

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from finance_ml.notebook_config import NotebookConfig
from finance_ml.ml_workflow.data.schema import (
    PHASE93_FEATURE_CATEGORIES,
    list_numeric_feature_cols,
    list_categorical_cols,
    list_date_cols,
    list_required_schema_columns_for_etl,
)

# Phase 9.3 Earnings Dashboard Widgets (code_guidelines.md §9.3, §17)

CFG = NotebookConfig(
    have_finance_prediction=True,
    have_database_connection=True,
    have_advanced_analytics=True,
    have_dim_reduction=False,
    debug_mode=False,
)

# ============================================================================
# Configuration Constants (code_guidelines.md Section 2.1 & 8.1)
# ============================================================================
from finance_ml.ml_workflow.config import (
    TARGET_COL,
    TARGET_COL_FALLBACK,
    TEST_SIZE,
    TRAIN_SIZE,
    CV_FOLDS,
    QUANTILES,
    MIN_SECTOR_SAMPLES,
    WINSORIZE_LOWER,
    WINSORIZE_UPPER,
    RANDOM_SEED,
    MODEL_VERSION,
)

# Derived & Notebook-Specific Constants
LOWER_QUANTILE = QUANTILES[0]
MEDIAN_QUANTILE = QUANTILES[1]
UPPER_QUANTILE = QUANTILES[2]
CONFIDENCE_LOW_THRESHOLD = 0.50
CONFIDENCE_MEDIUM_THRESHOLD = 0.75

# Sector/portfolio constraints
MAX_SECTOR_WEIGHT = 0.25
MAX_SINGLE_POSITION = 0.10

# Outlier detection
IQR_MULTIPLIER = 2.5
ZSCORE_THRESHOLD = 4.0

# Visualization Configuration
TOP_N_SECTORS = 12  # Top sectors for heatmaps/coverage
TOP_N_CATEGORIES = 8  # Top categories for radar charts
TOP_N_FEATURES = 10  # Number of features to display in detailed analysis

# Reproducibility & versioning
np.random.seed(RANDOM_SEED)

# Schema-Driven Column Selection
# Use canonical schema functions instead of hard-coded lists
NUMERIC_FEATURE_COLS = list_numeric_feature_cols()
CATEGORICAL_COLS = list_categorical_cols()
DATE_COLS = list_date_cols()
REQUIRED_ETL_COLS = list_required_schema_columns_for_etl(include_extended_financials=True)

# Key columns for summary statistics (subset of schema-driven numeric features)
KEY_SUMMARY_COLS = [
    'last_price', 'market_cap', 'enterprise_value',
    'ebitda_ltm', 'p_e_ntm', 'total_revenues_ltm'
]

# Section 17 Style Guidelines
plt.style.use('dark_background')
sns.set_palette('husl')
PLOTLY_TEMPLATE = 'plotly_dark'
COLOR_PALETTE = {
    'primary': '#375a7f',
    'secondary': '#6c757d',
    'success': '#00bc8c',
    'warning': '#f39c12',
    'danger': '#e74c3c',
    'info': '#3498db',
    'neutral': '#adb5bd',
}


def validate_configuration():
    """Validate notebook configuration constants (Section 2.3)."""
    # Validate target columns
    if not TARGET_COL or not isinstance(TARGET_COL, str):
        raise ValueError(f"TARGET_COL must be non-empty string: {TARGET_COL}")
    if not TARGET_COL_FALLBACK or not isinstance(TARGET_COL_FALLBACK, str):
        raise ValueError(f"TARGET_COL_FALLBACK must be non-empty string: {TARGET_COL_FALLBACK}")

    # Validate test size
    if not (0 < TEST_SIZE < 1):
        raise ValueError(f"TEST_SIZE must be between 0 and 1: {TEST_SIZE}")
    if not abs((TRAIN_SIZE + TEST_SIZE) - 1.0) < 0.01:
        raise ValueError(f"TRAIN_SIZE + TEST_SIZE must equal 1.0: {TRAIN_SIZE + TEST_SIZE}")

    # Validate CV folds
    if not isinstance(CV_FOLDS, int) or CV_FOLDS < 2:
        raise ValueError(f"CV_FOLDS must be integer >= 2: {CV_FOLDS}")

    # Validate quantiles
    if not QUANTILES or not isinstance(QUANTILES, list):
        raise ValueError(f"QUANTILES must be non-empty list: {QUANTILES}")
    for q in QUANTILES:
        if not (0 < q < 1):
            raise ValueError(f"All quantiles must be between 0 and 1: {q}")
    if QUANTILES != sorted(QUANTILES):
        raise ValueError(f"QUANTILES must be monotonically increasing: {QUANTILES}")

    # Validate sector configuration
    if not isinstance(MIN_SECTOR_SAMPLES, int) or MIN_SECTOR_SAMPLES < 1:
        raise ValueError(f"MIN_SECTOR_SAMPLES must be positive integer: {MIN_SECTOR_SAMPLES}")
    if not (0 < MAX_SECTOR_WEIGHT <= 1):
        raise ValueError(f"MAX_SECTOR_WEIGHT must be between 0 and 1: {MAX_SECTOR_WEIGHT}")

    # Validate outlier detection
    if IQR_MULTIPLIER <= 0:
        raise ValueError(f"IQR_MULTIPLIER must be positive: {IQR_MULTIPLIER}")
    if ZSCORE_THRESHOLD <= 0:
        raise ValueError(f"ZSCORE_THRESHOLD must be positive: {ZSCORE_THRESHOLD}")
    if not (0 <= WINSORIZE_LOWER < 0.5):
        raise ValueError(f"WINSORIZE_LOWER must be between 0 and 0.5: {WINSORIZE_LOWER}")
    if not (0.5 < WINSORIZE_UPPER <= 1):
        raise ValueError(f"WINSORIZE_UPPER must be between 0.5 and 1: {WINSORIZE_UPPER}")

    print("✓ All configuration constants validated successfully")
    return True


def convert_jdbc_to_sqlalchemy(jdbc_url: str) -> str:
    """Convert a JDBC PostgreSQL URL to a SQLAlchemy URL preserving credentials when present.

    Supported inputs:
    - jdbc:postgresql://host:port/db
    - jdbc:postgresql://user:password@host:port/db
    - jdbc:postgresql://host/db (port optional)

    Returns a postgresql+psycopg2 URL string.
    """
    import re

    pattern = re.compile(
        r"^jdbc:postgresql://(?:(?P<user>[^:@/]+)(?::(?P<pw>[^@/]*))?@)?(?P<host>[^:/?#]+)(?::(?P<port>\d+))?/(?P<db>[^?]+)"
    )
    m = pattern.match(jdbc_url)
    if not m:
        # Fallback: return as-is for caller to handle
        return jdbc_url
    user = m.group('user')
    pw = m.group('pw') or ''
    host = m.group('host')
    port = m.group('port') or '5432'
    db = m.group('db')
    if user:
        return f"postgresql+psycopg2://{user}:{pw}@{host}:{port}/{db}"
    # No credentials embedded
    return f"postgresql+psycopg2://{host}:{port}/{db}"


def check_db_connection(db_url: str) -> bool:
    """Return True if a quick test connection to the database succeeds, else False.

    Uses SQLAlchemy if available and performs a trivial SELECT 1. Exceptions are not raised.
    """
    if not HAVE_SQLALCHEMY or not db_url:
        return False
    try:
        engine = create_engine(db_url, pool_pre_ping=True)
        with engine.connect() as conn:
            conn.execute(text("SELECT 1"))
        return True
    except Exception:
        return False


# Database URL (env var or safe default)
DB_URL_ENV = os.getenv('DB_URL')
if DB_URL_ENV and DB_URL_ENV.startswith('jdbc:'):
    DB_URL = convert_jdbc_to_sqlalchemy(DB_URL_ENV)
elif DB_URL_ENV:
    DB_URL = DB_URL_ENV
else:
    # Safe default without credentials; aligns with docs but may not be reachable
    DB_URL = 'postgresql+psycopg2://localhost:5432/postgres'

# Run configuration validation
validate_configuration()

print('=' * 60)
print('ETL DATA EXPLORER - CONFIGURATION')
print('=' * 60)
print(f'PROJECT_ROOT: {PROJECT_ROOT}')
print(f'DATA_DIR: {DATA_DIR}')
print(f'Python: {sys.version.split()[0]}')
print(f'Random Seed: {RANDOM_SEED}')
print(f'Model Version: {MODEL_VERSION}')
CFG.display_summary()

✓ All configuration constants validated successfully
============================================================
ETL DATA EXPLORER - CONFIGURATION
============================================================
PROJECT_ROOT: C:\Users\markm\PycharmProjects\Finance_ML_Analytics_Platform
DATA_DIR: C:\Users\markm\PycharmProjects\Finance_ML_Analytics_Platform\data
Python: 3.14.0
Random Seed: 42
Model Version: v9_10
================================================================================
FEATURE FLAGS CONFIGURATION
================================================================================

Core Features:
  Financial Prediction:        ✓ Enabled
  Database Connection:         ✓ Enabled
  Advanced Analytics:          ✓ Enabled
  Dimensionality Reduction:    ✗ Disabled

Analysis Features:
  Sector Analysis:             ✓ Enabled
  Region Analysis:             ✓ Enabled

Output Features:
  Interactive Plots:           ✓ Enabled
  Excel Export:                ✓ Enabled
  Portfolio Optimization:      ✓ Enabled

Development:
  Debug Mode:                  ✗ Disabled
================================================================================

## Cell 2: Import Finance ML Modules

Import unified ETL pipeline, EDA analytics, and feature engineering modules.

In [2]:
# ============================================================================
# Cell 2: Import Finance ML Modules
# ============================================================================

# ETL Pipeline (Phase 9.1)
from finance_ml.ml_workflow.preprocessing.etl import (
    DataExtractionConfig,
    DataSanitizationConfig,
    DtypeCastingConfig,
    FeatureEngineeringConfig,
    FeatureSelectionConfig,
    FinancialMetricsConfig,
    ImputationConfig,
    ScalingConfig,
    SchemaValidationConfig,
    SemanticClassificationConfig,
    SemanticTransformConfig,
    etl_with_features,
    ETLConfig, )

# EDA Analytics (Phase 9.2)

# Phase 9.3 Feature Categories
from finance_ml.ml_workflow.eda.phase93_categories import (
    PHASE93_FEATURE_CATEGORIES,
    categorize_dataframe_columns,
    get_phase93_coverage_stats,
    list_all_phase93_features,
)

# Feature Engineering API (Phase 9.3)

# Column Semantics and Safety (Section 8.5)
from finance_ml.ml_workflow.preprocessing.column_semantics import (
    PRICE_COLUMNS,
)

print('✓ Finance ML modules imported successfully')
print(f'✓ Phase 9.3 Feature Categories: {len(PHASE93_FEATURE_CATEGORIES)} categories')
print(f'✓ Total Phase 9.3 Features: {len(list_all_phase93_features())} features')
print(f'✓ Price Columns Protected: {len(PRICE_COLUMNS)} columns')
print(f'\nFeature Engineering Presets Available:')
print(f"  - 'basic': core ratios, margins, volatility, revenue CAGR")
print(f"  - 'momentum': momentum & technical indicators")
print(f"  - 'quality': accounting quality and financial distress signals")
print(f"  - 'comprehensive': full advanced feature set (196 features)")

✓ Finance ML modules imported successfully
✓ Phase 9.3 Feature Categories: 21 categories
✓ Total Phase 9.3 Features: 295 features
✓ Price Columns Protected: 23 columns

Feature Engineering Presets Available:
  - 'basic': core ratios, margins, volatility, revenue CAGR
  - 'momentum': momentum & technical indicators
  - 'quality': accounting quality and financial distress signals
  - 'comprehensive': full advanced feature set (196 features)

## Cell 3: Database Configuration

Configure PostgreSQL database connection with automatic URL format conversion.

In [3]:
# ============================================================================
# Cell 3: Database Configuration
# ============================================================================

# SQL file paths
SQL_SCHEMA = PROJECT_ROOT / 'create_equities_schema.sql'
SQL_IMPORT = PROJECT_ROOT / 'import_equities_data.sql'

# Detect availability
have_db_url = DB_URL is not None and len(DB_URL) > 0
reachable_db = check_db_connection(DB_URL) if have_db_url else False
CFG.have_database_connection = bool(reachable_db)

print('=' * 60)
print('DATABASE CONFIGURATION')
print('=' * 60)
print(f'SQLAlchemy installed:  {HAVE_SQLALCHEMY}')
print(f'DB_URL configured:     {have_db_url}')
print(f'Database available:    {CFG.have_database_connection}')

if have_db_url:
    # Mask password for security
    try:
        parts = DB_URL.split('@')
        if len(parts) == 2:
            user_part = parts[0].split('//')[-1].split(':')[0]
            masked_url = f'postgresql://{user_part}@{parts[1]}'
        else:
            masked_url = 'postgresql://***@localhost:5432/postgres'
    except Exception:
        masked_url = 'postgresql://***'
    print(f'Connection:            {masked_url}')
else:
    print('Connection:            Not configured (will use CSV fallback)')

print(f'\nSQL Files:')
print(f"  Schema script:       {'✓' if SQL_SCHEMA.exists() else '✗'} {SQL_SCHEMA.name}")
print(f"  Import script:       {'✓' if SQL_IMPORT.exists() else '✗'} {SQL_IMPORT.name}")
print('=' * 60)

============================================================
DATABASE CONFIGURATION
============================================================
SQLAlchemy installed:  True
DB_URL configured:     True
Database available:    False
Connection:            postgresql://***@localhost:5432/postgres

SQL Files:
  Schema script:       ✓ create_equities_schema.sql
  Import script:       ✓ import_equities_data.sql
============================================================

In [4]:
# Phase 9.1: Unified ETL Pipeline with Automatic Fallback (code_guidelines.md Section 8.6)
# Recommended approach: Single etl_with_features() call with automatic fallback handling
# Replaces: Manual try/except blocks for CSV → DB fallback
# Reference: code_guidelines.md Section 8.6, finance_ml/ml_workflow/preprocessing/etl.py

FINANCIAL_METRICS_OUTPUT_DIR = Path("outputs/eda/financial_metrics")
FINANCIAL_METRICS_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

etl_config = ETLConfig(
    extraction=DataExtractionConfig(
        normalize_column_names=True,
    ),
    validation=SchemaValidationConfig(
        validate_schema=True,
        require_target_column=True,
        drop_rows_with_missing_critical_fields=True,
        validate_schema_alignment=True,
        schema_alignment_threshold=0.80,
    ),
    dtype_casting=DtypeCastingConfig(
        apply_dtype_casting=True,
        track_diagnostics=True,
    ),
    semantic_classification=SemanticClassificationConfig(
        enabled=False,
        preserve_price_columns=True,
    ),
    imputation=ImputationConfig(
        apply_imputation=True,
        strategy="6step",
        knn_neighbors=5,
        sector_column="sector",
        reference_price_column="last_price",
        impute_categorical_columns=True,
        impute_datetime_columns=True,
    ),
    semantic_transform=SemanticTransformConfig(
        apply_log_transforms=False,
        log_transform_method="log1p",
        log_transform_market_values=False,
        exclude_ratios_from_winsorization=True,
        exclude_percentages_from_winsorization=True,
        exclude_counts_from_scaling=True,
    ),
    sanitization=DataSanitizationConfig(
        sanitize_data=True,
        apply_winsorization=False,
        winsorize_lower_percentile=WINSORIZE_LOWER,
        winsorize_upper_percentile=WINSORIZE_UPPER,
    ),
    scaling=ScalingConfig(
        enabled=False,
        scaler_type="robust",
        scale_by_sector=True,
        exclude_price_columns=True,
    ),
    feature_engineering=FeatureEngineeringConfig(
        enabled=True,
        preset="comprehensive",
        engineer_earnings_analytics=True,  # NEW: Enable Earnings Quality (33 features)
    ),
    feature_selection=FeatureSelectionConfig(
        enabled=False,
        method="both",
        min_importance_threshold=0.01,
        max_correlation_threshold=0.95,
    ),
    financial_metrics=FinancialMetricsConfig(
        compute_valuation_metrics=True,
        compute_profitability_metrics=True,
        compute_growth_metrics=True,
        compute_leverage_metrics=True,
        compute_target_vs_price_metrics=True,
        compute_sector_specific_metrics=True,
        generate_quality_alerts=True,
        generate_metrics_dashboard=True,
        output_directory="financial_metrics",
    ),
)

## Cell 4: ETL Pipeline - Extract, Transform, Load

Run the unified ETL pipeline with 6-step imputation strategy.

In [5]:
# ============================================================================
# Cell 4: ETL Pipeline - Extract, Transform, Load
# ============================================================================

print('=' * 60)
print('ETL PIPELINE EXECUTION')
print('=' * 60)

# Complete ETL + financial metrics  and features
all_stocks_preprocessed, metrics = etl_with_features(
    source='csv',
    data_dir=DATA_DIR,
    return_metrics=True,
    config=etl_config
)

# Display ETL metrics summary
print('\n' + '=' * 60)
print(metrics.summary())
print('=' * 60)

# Validation checkpoint (Section 19.1 - REQUIRED)
assert not all_stocks_preprocessed.empty, 'Preprocessed data must not be empty'
assert 'ticker' in all_stocks_preprocessed.columns, 'ticker column must be present'
assert 'sector' in all_stocks_preprocessed.columns, 'sector column must be present'

# Validate target columns
target_cols = ['price_target', 'price_target_median', 'price_target_ytd_ago']
has_target = any(col in all_stocks_preprocessed.columns for col in target_cols)
assert has_target, f"At least one target column required: {target_cols}"

# Quality metrics validation
missing_pct = all_stocks_preprocessed.isna().sum().sum() / all_stocks_preprocessed.size * 100
assert missing_pct == 0, f"No missing values allowed after 6-step imputation, found {missing_pct:.2f}%"

# Data sufficiency validation
assert len(all_stocks_preprocessed) > 100, f"Insufficient data: {len(all_stocks_preprocessed)} rows (minimum 100)"
assert all_stocks_preprocessed['last_price'].min() > 0, "last_price must be positive"

# Stage naming alignment
all_stocks_preprocessed = all_stocks_preprocessed

print(f'\n✓ ETL Pipeline Complete')
print(f'  Data shape: {all_stocks_preprocessed.shape}')
print(f'  Source: {metrics.source_type}')
print(f'  Duration: {metrics.total_duration:.2f}s')
print(f'  Quality score: {metrics.quality_score:.3f}')
print(f'  Validation score: {metrics.validation_score:.3f}')
print(
    f'  Financial metrics added: {metrics.valuation_metrics_added + metrics.profitability_metrics_added + metrics.growth_metrics_added + metrics.leverage_metrics_added}')
print(f'  Missing values after imputation: {metrics.missing_values_after_imputation}')

============================================================
ETL PIPELINE EXECUTION
============================================================

WARNING:root:Business rule: Converted 8 negative values to NaN in 'enterprise_value' (must be >= 0)
WARNING:finance_ml.ml_workflow.preprocessing.imputation:WARNING: 27 NaN values still present
  Affected columns (1): ['fy_end']...
  Schema status: ['fy_end (in_schema)']
WARNING:finance_ml.ml_workflow.preprocessing.imputation:  Applying emergency fallback imputation...
WARNING:finance_ml.ml_workflow.preprocessing.etl:Skipped log-transform for 'total_revenues_1fy': 14 negative values present (added applicability flag)
WARNING:finance_ml.ml_workflow.preprocessing.etl:Skipped log-transform for 'net_income': 1034 negative values present (added applicability flag)
WARNING:finance_ml.ml_workflow.preprocessing.etl:Skipped log-transform for 'total_revenues_fq': 22 negative values present (added applicability flag)
WARNING:finance_ml.ml_workflow.preprocessing.etl:Skipped log-transform for 'total_revenues_ltm': 18 negative values present (added applicability flag)
WARNING:finance_ml.ml_workflow.preprocessing.etl:Skipped log-transform for 'capex': 6925 negative values present (added applicability flag)
WARNING:finance_ml.ml_workflow.preprocessing.etl:Skipped log-transform for 'revenue': 18 negative values present (added applicability flag)
WARNING:finance_ml.ml_workflow.preprocessing.etl:Skipped log-transform for 'total_operating_expenses_ltm': 6 negative values present (added applicability flag)
WARNING:finance_ml.ml_workflow.preprocessing.etl:Skipped log-transform for 'gross_profit': 122 negative values present (added applicability flag)
WARNING:finance_ml.ml_workflow.preprocessing.etl:Skipped log-transform for 'ebitda': 444 negative values present (added applicability flag)
WARNING:finance_ml.ml_workflow.preprocessing.etl:Skipped log-transform for 'total_revenues_fy': 17 negative values present (added applicability flag)
WARNING:finance_ml.ml_workflow.preprocessing.etl:Skipped log-transform for 'ebitda_ltm': 444 negative values present (added applicability flag)
WARNING:finance_ml.ml_workflow.preprocessing.etl:Skipped log-transform for 'ebitda_fq': 415 negative values present (added applicability flag)
WARNING:finance_ml.ml_workflow.preprocessing.etl:Skipped log-transform for 'operating_cash_flow': 860 negative values present (added applicability flag)
WARNING:finance_ml.ml_workflow.preprocessing.etl:Skipped log-transform for 'total_equity': 119 negative values present (added applicability flag)
WARNING:finance_ml.ml_workflow.preprocessing.etl:Skipped log-transform for 'ebitda_fy': 478 negative values present (added applicability flag)
WARNING:finance_ml.ml_workflow.preprocessing.etl:Skipped log-transform for 'operating_income': 673 negative values present (added applicability flag)
WARNING:finance_ml.ml_workflow.preprocessing.imputation:WARNING: 33 NaN values still present
  Affected columns (2): ['ma_20d', 'ma_50d']...
  Schema status: ['ma_20d (in_schema)', 'ma_50d (in_schema)']
WARNING:finance_ml.ml_workflow.preprocessing.imputation:  Applying emergency fallback imputation...
WARNING:finance_ml.ml_workflow.preprocessing.etl:Found 7 unknown columns not in COLUMN_SCHEMA or allowlist
WARNING:finance_ml.ml_workflow.preprocessing.etl:Unknown columns: ['_reference_date_formatted', 'dividend_record_ex_date_formatted', 'fiscal_quarter_inferred', 'fy_end_formatted', 'fy_end_vs_isrd_days', 'income_statement_report_date_formatted', 'next_earnings_formatted']

============================================================
ETL Pipeline Summary:
  Source: csv
  Duration: 2.21s (extract: 0.24s, transform: 1.87s, load: 0.10s)
  Data: 6982 → 6981 rows, 382 → 682 columns
  Dtype Casting: Applied (0 coercion warnings, 0 unknown columns) ✓
  Imputation: 6step (11394 → 0 missing) ✓
  Scaling: None (0 columns) Price Protected: ✓
  Financial Metrics: 23 added (valuation: 4, profitability: 5, growth: 3, leverage: 2)
  Semantic Classification: ✓ (Price Columns: 21, Market Value: 21, Ratios: 45, Log-Transformed: 5)
  Feature Engineering: comprehensive (255 features added)
  Business Rules: ⚠ (8 negative value violations sanitized, 16 log-transforms skipped)
  Schema Validation: ✓ (alignment: 98.97%, unknown extra: 7, missing required: 0, dtype mismatches: 0, recognized: 675)
  Quality: 1.000, Validation: 0.857
============================================================

✓ ETL Pipeline Complete
  Data shape: (6981, 682)
  Source: csv
  Duration: 2.21s
  Quality score: 1.000
  Validation score: 0.857
  Financial metrics added: 14
  Missing values after imputation: 0

## Cell 5: Data Quality Overview

Examine data shape, dtypes, and missing values post-imputation.

In [6]:
# ============================================================================
# Cell 5: Data Quality Overview
# ============================================================================

print('=' * 60)
print('DATA QUALITY OVERVIEW')
print('=' * 60)

# Basic info
print(f'\nDataFrame Shape: {all_stocks_preprocessed.shape[0]:,} rows × {all_stocks_preprocessed.shape[1]} columns')
print(f'Memory Usage: {all_stocks_preprocessed.memory_usage(deep=True).sum() / 1024 ** 2:.2f} MB')

# Data types summary
dtype_counts = all_stocks_preprocessed.dtypes.value_counts()
print(f'\nData Types:')
for dtype, count in dtype_counts.items():
    print(f'  {dtype}: {count} columns')

# Missing values (post-imputation)
missing = all_stocks_preprocessed.isnull().sum()
missing_pct = (missing / len(all_stocks_preprocessed) * 100).round(2)
missing_df = pd.DataFrame({
    'Column': missing.index,
    'Missing': missing.values,
    'Percent': missing_pct.values
}).query('Missing > 0').sort_values('Missing', ascending=False)

if len(missing_df) > 0:
    print(f'\n⚠ Columns with missing values (Top 10):')
    print(missing_df.head(10).to_string(index=False))
else:
    print(f'\n✓ No missing values - imputation successful!')

# Summary statistics for key columns
print(f'\nSummary Statistics (key numeric columns):')
key_cols = ['last_price', 'market_cap', 'enterprise_value', 'ebitda_ltm', 'p_e_ntm']
available_keys = [c for c in key_cols if c in all_stocks_preprocessed.columns]
if available_keys:
    print(all_stocks_preprocessed[available_keys].describe().round(2).to_string())

============================================================
DATA QUALITY OVERVIEW
============================================================

DataFrame Shape: 6,981 rows × 682 columns
Memory Usage: 43.30 MB

Data Types:
  float64: 456 columns
  float32: 170 columns
  bool: 23 columns
  string: 13 columns
  datetime64[ns]: 8 columns
  category: 1 columns
  category: 1 columns
  category: 1 columns
  category: 1 columns
  category: 1 columns
  category: 1 columns
  category: 1 columns
  category: 1 columns
  category: 1 columns
  category: 1 columns
  datetime64[us]: 1 columns
  category: 1 columns

✓ No missing values - imputation successful!

Summary Statistics (key numeric columns):
       last_price  market_cap  enterprise_value  ebitda_ltm  p_e_ntm
count     6981.00     6981.00           6981.00     6981.00  6981.00
mean      4316.88    19058.08          20150.38     1428.95    22.96
std      48677.39   115432.04         115377.79     6104.36    30.53
min          0.01        5.70              2.39    -6154.00     0.00
25%         14.26     1734.15           2336.12      117.16    11.50
50%         43.56     4478.13           5254.76      358.17    15.90
75%        154.00    11477.16          12114.12      940.22    22.90
max    1850000.00  4397876.01        4348090.01   217535.33   497.90

In [7]:
all_stocks_preprocessed

,ticker,isin,name,description,region,country,trading_country,exchange,unit,sector,...,net_income_adjustment_spread_fy,ebitda_adjustment_spread_ltm,ebitda_adjustment_pct_ltm,ebitda_adjustment_spread_fy,ebit_adjustment_spread_ltm,ebit_adjustment_pct_ltm,ebit_adjustment_spread_fy,adjustment_consistency_score,earnings_quality_warning_flag,exceptional_items_impact_ratio
0,NVDA,US67066G1040,NVIDIA Corporation,NVIDIA Corporation a computing infrastructure ...,United States and Canada,US,US,NasdaqGS,USD,Information Technology,...,1385.00,1742.000,1.545751,0.000,6586.000,5.980640,5336.00,99.540148,False,0.000306
1,AAPL,US0378331005,Apple Inc.,Apple Inc. designs manufactures and markets sm...,United States and Canada,US,US,NasdaqGS,USD,Information Technology,...,0.00,-253.000,-0.174787,-253.000,0.000,0.000000,0.00,99.933244,False,0.000271
2,GOOGL,US02079K3059,Alphabet Inc.,Alphabet Inc. offers various products and plat...,United States and Canada,US,US,NasdaqGS,USD,Communication Services,...,0.00,21896.000,15.082591,20989.000,-1796.000,-1.426835,-1796.00,99.837884,False,0.014573
3,MSFT,US5949181045,Microsoft Corporation,Microsoft Corporation develops and supports so...,United States and Canada,US,US,NasdaqGS,USD,Information Technology,...,0.00,9331.000,5.606326,6153.000,0.000,0.000000,0.00,98.505330,False,0.000289
4,AMZN,US0231351067,Amazon.com Inc.,Amazon.com Inc. engages in the retail sale of ...,United States and Canada,US,US,NasdaqGS,USD,Consumer Discretionary,...,0.00,22043.000,15.779151,23694.000,-2500.000,-3.176580,0.00,99.684923,False,0.000397
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6977,BHL,TN0006720049,BH Leasing Société Anonyme,BH Leasing Société Anonyme engages in the leas...,Africa / Middle East,TN,TN,BVMT,TND,Real Estate,...,0.00,117.015,32.670240,74.455,106.115,43.875463,-216.18,0.000000,True,40.446665
6978,BERGER,NGBERGER0000,Berger Paints Nigeria Plc,Berger Paints Nigeria Plc manufactures distrib...,Africa / Middle East,NG,NG,NGSE,NGN,Materials,...,191.99,473.475,27688.596491,401.380,346.460,22944.370861,281.38,76.969672,True,32.618279
6979,SOTET,TN0006530018,Société Tunisienne d'Entreprises de Télécommun...,Société Tunisienne d'Entreprises de Télécommun...,Africa / Middle East,TN,TN,BVMT,TND,Communication Services,...,0.00,473.235,24268.461538,0.330,346.510,23733.561644,-0.01,0.000000,True,40.446665
6980,SCB,TN0007350010,Les Ciments de Bizerte,Les Ciments de Bizerte manufactures sells and ...,Africa / Middle East,TN,TN,BVMT,TND,Materials,...,0.00,480.125,9719.129555,0.490,360.060,2978.163772,0.00,66.919193,True,1.959625
6981,SOKNA,TN0007210016,Essoukna,Essoukna engages in the real estate business i...,Africa / Middle East,TN,TN,BVMT,TND,Real Estate,...,-0.21,474.325,55154.069767,0.000,347.110,40361.627907,0.00,0.000000,True,168.527773

## Cell 6: Phase 9.3 Feature Engineering

**Business Goal:** Engineer comprehensive financial features including valuation ratios, profitability metrics, quality indicators, and sector-specific features to maximize model predictive power.

**Key Objectives:**
1. Engineer valuation ratios (P/E, P/B, EV/EBITDA, PEG)
2. Engineer profitability features (margins, ROE, ROA, ROIC)
3. Create momentum and technical indicators
4. Engineer analyst quality features
5. Create accounting quality scores (Altman Z, Piotroski F)
6. Build sector-relative features
7. Create interaction features

In [8]:
# ============================================================================
# Cell 6: Phase 9.3 Feature Engineering
# ============================================================================


# Phase 9.3 Enhanced Benchmarking Analysis
print('\n' + '=' * 80)
print('📊 Phase 9.3 Enhanced Benchmarking Analysis:')
print('=' * 80)

# Categorize features by Phase 9.3 families
categorized = categorize_dataframe_columns(all_stocks_preprocessed)
coverage_stats = get_phase93_coverage_stats(all_stocks_preprocessed)

# Calculate total Phase 9.3 features present
total_phase93_features = sum(coverage_stats.values())
expected_counts = {cat: len(features) for cat, features in PHASE93_FEATURE_CATEGORIES.items()}
total_expected = sum(expected_counts.values())

print(f'\n✓ Analyzing engineered features DataFrame')
print(f'  Total stocks: {all_stocks_preprocessed.shape[0]}')
print(f'  Total columns: {all_stocks_preprocessed.shape[1]}')
print(
    '  Phase 9.3 engineered features present: {total_phase93_features}/{total_expected} ({total_phase93_features / total_expected * 100:.1f}%)')

if 'sector' in all_stocks_preprocessed.columns:
    print(f'  Sectors analyzed: {all_stocks_preprocessed["sector"].nunique()}')
if 'region' in all_stocks_preprocessed.columns:
    print(f'  Regions analyzed: {all_stocks_preprocessed["region"].nunique()}')

# Show coverage by category
print(f'\n📋 Phase 9.3 Feature Coverage by Category:')
print('=' * 80)

for category in sorted(PHASE93_FEATURE_CATEGORIES.keys()):
    present = coverage_stats.get(category, 0)
    expected = expected_counts[category]

    if present > 0:
        pct = (present / expected * 100) if expected > 0 else 0
        print(f'  ✓ {category}: {present}/{expected} features ({pct:.1f}% coverage)')

        # Show sample features for this category
        if category in categorized:
            sample_features = categorized[category][:3]
            for feat in sample_features:
                non_null = all_stocks_preprocessed[feat].notna().sum()
                print(f'      • {feat}: {non_null}/{len(all_stocks_preprocessed)} non-null')
    else:
        print(f'  ✗ {category}: 0/{expected} features (not yet engineered)')

# Summary
print(f'\n📊 Benchmarking Summary:')
print('=' * 80)
categories_with_features = len([c for c in coverage_stats.values() if c > 0])
print(f'  Categories with features: {categories_with_features}/{len(PHASE93_FEATURE_CATEGORIES)}')
print(f'  Total Phase 9.3 features: {total_phase93_features}')
print(f'  Overall coverage: {total_phase93_features / total_expected * 100:.1f}%')

# Export benchmarking report
benchmarking_report_path = OUTPUT_DIR / 'eda' / 'phase93_benchmarking_etl_explorer.json'
benchmarking_summary = {
    'phase': '9.3',
    'data_source': 'all_stocks_preprocessed DataFrame (ETL Data Explorer)',
    'timestamp': pd.Timestamp.now().isoformat(),
    'total_stocks': int(all_stocks_preprocessed.shape[0]),
    'total_columns': int(all_stocks_preprocessed.shape[1]),
    'phase93_features_present': int(total_phase93_features),
    'phase93_features_expected': int(total_expected),
    'coverage_percentage': float(total_phase93_features / total_expected * 100),
    'category_coverage': {
        cat: {
            'present': int(coverage_stats.get(cat, 0)),
            'expected': int(expected_counts[cat]),
            'coverage_pct': float(
                (coverage_stats.get(cat, 0) / expected_counts[cat] * 100) if expected_counts[cat] > 0 else 0)
        }
        for cat in PHASE93_FEATURE_CATEGORIES.keys()
    },
    'categories_with_features': categories_with_features,

}

with open(benchmarking_report_path, 'w') as f:
    json.dump(benchmarking_summary, f, indent=2)
print(f'\n✓ Benchmarking report saved to: {benchmarking_report_path}')

================================================================================
📊 Phase 9.3 Enhanced Benchmarking Analysis:
================================================================================

✓ Analyzing engineered features DataFrame
  Total stocks: 6981
  Total columns: 682
  Phase 9.3 engineered features present: {total_phase93_features}/{total_expected} ({total_phase93_features / total_expected * 100:.1f}%)
  Sectors analyzed: 11
  Regions analyzed: 5

📋 Phase 9.3 Feature Coverage by Category:
================================================================================
  ✓ Analyst Sentiment: 10/10 features (100.0% coverage)
      • price_target_spread_pct: 6981/6981 non-null
      • price_target_range: 6981/6981 non-null
      • consensus_strength: 6981/6981 non-null
  ✓ Balance Sheet Dynamics: 5/9 features (55.6% coverage)
      • balance_sheet_expansion: 6981/6981 non-null
      • current_ratio_trend: 6981/6981 non-null
      • working_capital_ratio: 6981/6981 non-null
  ✓ Capital Allocation: 21/23 features (91.3% coverage)
      • div_yield_ltm: 6981/6981 non-null
      • capex_intensity: 6981/6981 non-null
      • working_capital_efficiency: 6981/6981 non-null
  ✓ Cash Flow: 5/5 features (100.0% coverage)
      • cfo_to_net_income: 6981/6981 non-null
      • fcf_to_net_income: 6981/6981 non-null
      • fcf_margin: 6981/6981 non-null
  ✓ Composite Scores: 5/5 features (100.0% coverage)
      • piotroski_f_score: 6981/6981 non-null
      • altman_z_score: 6981/6981 non-null
      • beneish_m_score: 6981/6981 non-null
  ✗ Dividend Reliability: 0/12 features (not yet engineered)
  ✓ Earnings Quality: 32/33 features (97.0% coverage)
      • net_income_adjustment_ratio_ltm: 6981/6981 non-null
      • net_income_adjustment_ratio_fy: 6981/6981 non-null
      • eps_surprise_pct: 6981/6981 non-null
  ✓ Efficiency Ratios: 4/4 features (100.0% coverage)
      • asset_turnover: 6981/6981 non-null
      • inventory_turnover: 6981/6981 non-null
      • receivables_turnover: 6981/6981 non-null
  ✓ Employee Productivity: 21/21 features (100.0% coverage)
      • profit_per_employee: 6981/6981 non-null
      • assets_per_employee: 6981/6981 non-null
      • ebitda_per_employee: 6981/6981 non-null
  ✗ Employment Dynamics: 0/10 features (not yet engineered)
  ✓ Growth Metrics: 9/9 features (100.0% coverage)
      • revenue_growth: 6981/6981 non-null
      • ebitda_growth: 6981/6981 non-null
      • earnings_growth: 6981/6981 non-null
  ✓ Leverage & Liquidity: 8/9 features (88.9% coverage)
      • debt_to_equity: 6981/6981 non-null
      • debt_to_assets: 6981/6981 non-null
      • interest_coverage: 6981/6981 non-null
  ✓ Market Sentiment: 5/6 features (83.3% coverage)
      • one_day_chg: 6981/6981 non-null
      • beta_stability: 6981/6981 non-null
      • systematic_risk_trend: 6981/6981 non-null
  ✓ Momentum & Technical: 25/25 features (100.0% coverage)
      • price_momentum_1m: 6981/6981 non-null
      • price_momentum_3m: 6981/6981 non-null
      • price_momentum_6m: 6981/6981 non-null
  ✓ Profitability: 14/14 features (100.0% coverage)
      • gross_margin_pct: 6981/6981 non-null
      • operating_margin_pct: 6981/6981 non-null
      • net_margin_pct: 6981/6981 non-null
  ✓ Quality & Risk: 18/18 features (100.0% coverage)
      • has_goodwill_impairment: 6981/6981 non-null
      • goodwill_impairment_flag: 6981/6981 non-null
      • has_asset_writedown: 6981/6981 non-null
  ✓ Revenue Forecasting: 9/9 features (100.0% coverage)
      • revenue_estimate_spread_ntm: 6981/6981 non-null
      • revenue_estimate_spread_fy1e: 6981/6981 non-null
      • revenue_consensus_uncertainty_score: 6981/6981 non-null
  ✗ Technical Analysis: 0/15 features (not yet engineered)
  ✓ Temporal Patterns: 17/17 features (100.0% coverage)
      • last_updated: 6981/6981 non-null
      • income_statement_report_date: 6981/6981 non-null
      • next_earnings: 6981/6981 non-null
  ✓ Valuation Ratios: 24/25 features (96.0% coverage)
      • p_b: 6981/6981 non-null
      • p_e_ratio: 6981/6981 non-null
      • p_s_ratio: 6981/6981 non-null
  ✗ Valuation Timeseries: 0/16 features (not yet engineered)

📊 Benchmarking Summary:
================================================================================
  Categories with features: 17/21
  Total Phase 9.3 features: 232
  Overall coverage: 78.6%

✓ Benchmarking report saved to: C:\Users\markm\PycharmProjects\Finance_ML_Analytics_Platform\outputs\eda\phase93_benchmarking_etl_explorer.json

In [9]:
all_stocks_preprocessed

,ticker,isin,name,description,region,country,trading_country,exchange,unit,sector,...,net_income_adjustment_spread_fy,ebitda_adjustment_spread_ltm,ebitda_adjustment_pct_ltm,ebitda_adjustment_spread_fy,ebit_adjustment_spread_ltm,ebit_adjustment_pct_ltm,ebit_adjustment_spread_fy,adjustment_consistency_score,earnings_quality_warning_flag,exceptional_items_impact_ratio
0,NVDA,US67066G1040,NVIDIA Corporation,NVIDIA Corporation a computing infrastructure ...,United States and Canada,US,US,NasdaqGS,USD,Information Technology,...,1385.00,1742.000,1.545751,0.000,6586.000,5.980640,5336.00,99.540148,False,0.000306
1,AAPL,US0378331005,Apple Inc.,Apple Inc. designs manufactures and markets sm...,United States and Canada,US,US,NasdaqGS,USD,Information Technology,...,0.00,-253.000,-0.174787,-253.000,0.000,0.000000,0.00,99.933244,False,0.000271
2,GOOGL,US02079K3059,Alphabet Inc.,Alphabet Inc. offers various products and plat...,United States and Canada,US,US,NasdaqGS,USD,Communication Services,...,0.00,21896.000,15.082591,20989.000,-1796.000,-1.426835,-1796.00,99.837884,False,0.014573
3,MSFT,US5949181045,Microsoft Corporation,Microsoft Corporation develops and supports so...,United States and Canada,US,US,NasdaqGS,USD,Information Technology,...,0.00,9331.000,5.606326,6153.000,0.000,0.000000,0.00,98.505330,False,0.000289
4,AMZN,US0231351067,Amazon.com Inc.,Amazon.com Inc. engages in the retail sale of ...,United States and Canada,US,US,NasdaqGS,USD,Consumer Discretionary,...,0.00,22043.000,15.779151,23694.000,-2500.000,-3.176580,0.00,99.684923,False,0.000397
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6977,BHL,TN0006720049,BH Leasing Société Anonyme,BH Leasing Société Anonyme engages in the leas...,Africa / Middle East,TN,TN,BVMT,TND,Real Estate,...,0.00,117.015,32.670240,74.455,106.115,43.875463,-216.18,0.000000,True,40.446665
6978,BERGER,NGBERGER0000,Berger Paints Nigeria Plc,Berger Paints Nigeria Plc manufactures distrib...,Africa / Middle East,NG,NG,NGSE,NGN,Materials,...,191.99,473.475,27688.596491,401.380,346.460,22944.370861,281.38,76.969672,True,32.618279
6979,SOTET,TN0006530018,Société Tunisienne d'Entreprises de Télécommun...,Société Tunisienne d'Entreprises de Télécommun...,Africa / Middle East,TN,TN,BVMT,TND,Communication Services,...,0.00,473.235,24268.461538,0.330,346.510,23733.561644,-0.01,0.000000,True,40.446665
6980,SCB,TN0007350010,Les Ciments de Bizerte,Les Ciments de Bizerte manufactures sells and ...,Africa / Middle East,TN,TN,BVMT,TND,Materials,...,0.00,480.125,9719.129555,0.490,360.060,2978.163772,0.00,66.919193,True,1.959625
6981,SOKNA,TN0007210016,Essoukna,Essoukna engages in the real estate business i...,Africa / Middle East,TN,TN,BVMT,TND,Real Estate,...,-0.21,474.325,55154.069767,0.000,347.110,40361.627907,0.00,0.000000,True,168.527773

## Cell 6.5: Phase 9.3 Feature Category Visualizations

Interactive visualizations for the 16 Phase 9.3 feature categories (196 total features).

**Key Visualizations:**
1. **Feature Category Treemap** - Hierarchical view of all 196 features across 16 categories
2. **Category Coverage Bar Chart** - Coverage percentage by category with expected vs present counts
3. **Category-Sector Feature Heatmap** - Feature availability by category across sectors
4. **Feature Completeness Radar** - Multi-dimensional view of feature coverage quality
5. **Category Distribution Sunburst** - Interactive drill-down by category → feature

In [10]:
# ============================================================================
# Cell 6.5: Phase 9.3 Feature Category Visualizations
# ============================================================================

print('=' * 80)
print('PHASE 9.3 FEATURE CATEGORY VISUALIZATIONS')
print('=' * 80)

# Create output directory for feature category visualizations
feature_viz_dir = OUTPUT_DIR / 'eda' / 'phase93_feature_categories'
feature_viz_dir.mkdir(parents=True, exist_ok=True)

# ============================================================================
# 1. Feature Category Treemap
# ============================================================================
print('\n📊 Generating Feature Category Treemap...')

# Build treemap data from PHASE93_FEATURE_CATEGORIES
treemap_data = []
for category, features in PHASE93_FEATURE_CATEGORIES.items():
    for feature in features:
        # Check if feature exists in dataframe and calculate completeness
        if feature in all_stocks_preprocessed.columns:
            completeness = (all_stocks_preprocessed[feature].notna().sum() / len(all_stocks_preprocessed)) * 100
            present = True
        else:
            completeness = 0
            present = False

        treemap_data.append({
            'Category': category,
            'Feature': feature,
            'Present': present,
            'Completeness': completeness,
            'Value': 1,  # Equal weight for treemap sizing
        })

treemap_df = pd.DataFrame(treemap_data)

# Create treemap with color based on completeness
fig_treemap = px.treemap(
    treemap_df,
    path=['Category', 'Feature'],
    values='Value',
    color='Completeness',
    color_continuous_scale='RdYlGn',
    title='<b>Phase 9.3 Feature Categories (196 Features)</b><br><sup>Color = Data Completeness (%)</sup>',
)
fig_treemap.update_layout(
    template=PLOTLY_TEMPLATE,
    height=800,
    font=dict(family='Segoe UI, Roboto, Arial'),
    title_font_size=20,
)
fig_treemap.update_traces(
    hovertemplate='<b>%{label}</b><br>Completeness: %{color:.1f}%<extra></extra>',
)
fig_treemap.write_html(feature_viz_dir / 'phase93_feature_treemap.html')
print(f'  ✓ Saved: phase93_feature_treemap.html')
fig_treemap.show()

# ============================================================================
# 2. Category Coverage Bar Chart
# ============================================================================
print('\n📈 Generating Category Coverage Bar Chart...')

# Build coverage data
coverage_data = []
for category in PHASE93_FEATURE_CATEGORIES.keys():
    expected = len(PHASE93_FEATURE_CATEGORIES[category])
    present = coverage_stats.get(category, 0)
    coverage_pct = (present / expected * 100) if expected > 0 else 0

    # Calculate average completeness for present features
    avg_completeness = 0
    if category in categorized and categorized[category]:
        completeness_values = []
        for feat in categorized[category]:
            if feat in all_stocks_preprocessed.columns:
                comp = (all_stocks_preprocessed[feat].notna().sum() / len(all_stocks_preprocessed)) * 100
                completeness_values.append(comp)
        if completeness_values:
            avg_completeness = np.mean(completeness_values)

    coverage_data.append({
        'Category': category,
        'Expected': expected,
        'Present': present,
        'Coverage %': coverage_pct,
        'Avg Completeness %': avg_completeness,
    })

coverage_df = pd.DataFrame(coverage_data).sort_values('Expected', ascending=True)

# Create grouped bar chart
fig_coverage = make_subplots(
    rows=1, cols=2,
    subplot_titles=['Feature Count (Expected vs Present)', 'Coverage & Completeness Quality'],
    horizontal_spacing=0.15,
)

# Expected vs Present bars
fig_coverage.add_trace(
    go.Bar(
        y=coverage_df['Category'],
        x=coverage_df['Expected'],
        name='Expected',
        orientation='h',
        marker_color=COLOR_PALETTE['neutral'],
        hovertemplate='<b>%{y}</b><br>Expected: %{x}<extra></extra>',
    ),
    row=1, col=1
)
fig_coverage.add_trace(
    go.Bar(
        y=coverage_df['Category'],
        x=coverage_df['Present'],
        name='Present',
        orientation='h',
        marker_color=COLOR_PALETTE['success'],
        hovertemplate='<b>%{y}</b><br>Present: %{x}<extra></extra>',
    ),
    row=1, col=1
)

# Coverage % and Completeness % bars
fig_coverage.add_trace(
    go.Bar(
        y=coverage_df['Category'],
        x=coverage_df['Coverage %'],
        name='Coverage %',
        orientation='h',
        marker_color=COLOR_PALETTE['primary'],
        hovertemplate='<b>%{y}</b><br>Coverage: %{x:.1f}%<extra></extra>',
    ),
    row=1, col=2
)
fig_coverage.add_trace(
    go.Bar(
        y=coverage_df['Category'],
        x=coverage_df['Avg Completeness %'],
        name='Avg Completeness %',
        orientation='h',
        marker_color=COLOR_PALETTE['secondary'],
        hovertemplate='<b>%{y}</b><br>Completeness: %{x:.1f}%<extra></extra>',
    ),
    row=1, col=2
)

fig_coverage.update_layout(
    title='<b>Phase 9.3 Category Coverage Analysis</b><br><sup>16 Categories, 196 Total Features</sup>',
    template=PLOTLY_TEMPLATE,
    height=700,
    font=dict(family='Segoe UI, Roboto, Arial'),
    title_font_size=20,
    barmode='group',
    showlegend=True,
    legend=dict(orientation='h', yanchor='bottom', y=-0.15, xanchor='center', x=0.5),
)
fig_coverage.update_xaxes(title='Count', row=1, col=1)
fig_coverage.update_xaxes(title='Percentage (%)', row=1, col=2)
fig_coverage.write_html(feature_viz_dir / 'phase93_category_coverage.html')
print(f'  ✓ Saved: phase93_category_coverage.html')
fig_coverage.show()

# ============================================================================
# 3. Category-Sector Feature Heatmap
# ============================================================================
print('\n🔥 Generating Category-Sector Feature Heatmap...')

if 'sector' in all_stocks_preprocessed.columns:
    # Calculate feature availability by sector for each category
    top_sectors = all_stocks_preprocessed['sector'].value_counts().head(12).index.tolist()

    heatmap_data = []
    for sector in top_sectors:
        sector_df = all_stocks_preprocessed[all_stocks_preprocessed['sector'] == sector]
        sector_row = {'Sector': str(sector)[:25]}

        for category in PHASE93_FEATURE_CATEGORIES.keys():
            if category in categorized and categorized[category]:
                # Calculate average completeness for this category in this sector
                completeness_values = []
                for feat in categorized[category]:
                    if feat in sector_df.columns:
                        comp = (sector_df[feat].notna().sum() / len(sector_df)) * 100
                        completeness_values.append(comp)
                sector_row[category] = np.mean(completeness_values) if completeness_values else 0
            else:
                sector_row[category] = 0

        heatmap_data.append(sector_row)

    heatmap_df = pd.DataFrame(heatmap_data).set_index('Sector')

    # Create heatmap
    fig_heatmap = px.imshow(
        heatmap_df,
        title='<b>Phase 9.3 Feature Completeness by Sector × Category</b><br><sup>Average Data Completeness (%) - Green = High Quality</sup>',
        template=PLOTLY_TEMPLATE,
        color_continuous_scale='RdYlGn',
        aspect='auto',
        text_auto='.0f',
    )
    fig_heatmap.update_layout(
        height=600,
        font=dict(family='Segoe UI, Roboto, Arial'),
        title_font_size=20,
        xaxis_title='Feature Category',
        yaxis_title='Sector',
    )
    fig_heatmap.update_xaxes(tickangle=45)
    fig_heatmap.write_html(feature_viz_dir / 'phase93_category_sector_heatmap.html')
    print(f'  ✓ Saved: phase93_category_sector_heatmap.html')
    fig_heatmap.show()
else:
    print('  ⚠ Sector column not available for heatmap')

# ============================================================================
# 4. Feature Completeness Radar Chart
# ============================================================================
print('\n🎯 Generating Feature Completeness Radar Chart...')

# Prepare radar data - top 8 categories by feature count
top_categories = sorted(PHASE93_FEATURE_CATEGORIES.keys(),
                        key=lambda x: len(PHASE93_FEATURE_CATEGORIES[x]),
                        reverse=True)[:8]

radar_data = []
for cat in top_categories:
    cat_coverage = coverage_df[coverage_df['Category'] == cat]
    if not cat_coverage.empty:
        radar_data.append({
            'Category': cat.replace(' & ', '/').replace(' ', '\n')[:15],
            'Coverage': cat_coverage['Coverage %'].values[0],
            'Completeness': cat_coverage['Avg Completeness %'].values[0],
        })

if radar_data:
    radar_df = pd.DataFrame(radar_data)

    fig_radar = go.Figure()

    # Add coverage trace
    fig_radar.add_trace(go.Scatterpolar(
        r=radar_df['Coverage'].tolist() + [radar_df['Coverage'].iloc[0]],
        theta=radar_df['Category'].tolist() + [radar_df['Category'].iloc[0]],
        fill='toself',
        name='Coverage %',
        line_color=COLOR_PALETTE['primary'],
        fillcolor=f"rgba(99, 102, 241, 0.3)",
    ))

    # Add completeness trace
    fig_radar.add_trace(go.Scatterpolar(
        r=radar_df['Completeness'].tolist() + [radar_df['Completeness'].iloc[0]],
        theta=radar_df['Category'].tolist() + [radar_df['Category'].iloc[0]],
        fill='toself',
        name='Completeness %',
        line_color=COLOR_PALETTE['success'],
        fillcolor=f"rgba(16, 185, 129, 0.3)",
    ))

    fig_radar.update_layout(
        polar=dict(
            radialaxis=dict(visible=True, range=[0, 100]),
            bgcolor='rgba(0,0,0,0)',
        ),
        title='<b>Feature Quality Radar: Top 8 Categories</b><br><sup>Coverage = Feature Presence, Completeness = Data Quality</sup>',
        template=PLOTLY_TEMPLATE,
        height=600,
        font=dict(family='Segoe UI, Roboto, Arial'),
        title_font_size=20,
        showlegend=True,
        legend=dict(orientation='h', yanchor='bottom', y=-0.15, xanchor='center', x=0.5),
    )
    fig_radar.write_html(feature_viz_dir / 'phase93_feature_radar.html')
    print(f'  ✓ Saved: phase93_feature_radar.html')
    fig_radar.show()

# ============================================================================
# 5. Category Distribution Sunburst
# ============================================================================
print('\n🌐 Generating Category Distribution Sunburst...')

# Build sunburst data with category -> subcategory structure
sunburst_data = []
category_groups = {
    'Financial': ['Valuation Ratios', 'Profitability', 'Cash Flow', 'Leverage & Liquidity'],
    'Market': ['Momentum & Technical', 'Market Sentiment', 'Analyst Sentiment'],
    'Quality': ['Quality & Risk', 'Composite Scores', 'Efficiency Ratios'],
    'Growth': ['Growth Metrics', 'Revenue Forecasting', 'Capital Allocation'],
    'Operations': ['Employee Productivity', 'Balance Sheet Dynamics', 'Temporal Patterns'],
}

for group, categories in category_groups.items():
    for category in categories:
        if category in PHASE93_FEATURE_CATEGORIES:
            present = coverage_stats.get(category, 0)
            expected = len(PHASE93_FEATURE_CATEGORIES[category])
            sunburst_data.append({
                'Group': group,
                'Category': category,
                'Features': expected,
                'Present': present,
                'Coverage': (present / expected * 100) if expected > 0 else 0,
            })

if sunburst_data:
    sunburst_df = pd.DataFrame(sunburst_data)

    fig_sunburst = px.sunburst(
        sunburst_df,
        path=['Group', 'Category'],
        values='Features',
        color='Coverage',
        color_continuous_scale='RdYlGn',
        title='<b>Phase 9.3 Feature Taxonomy</b><br><sup>Hierarchical View: Group → Category (Color = Coverage %)</sup>',
    )
    fig_sunburst.update_layout(
        template=PLOTLY_TEMPLATE,
        height=700,
        font=dict(family='Segoe UI, Roboto, Arial'),
        title_font_size=20,
    )
    fig_sunburst.write_html(feature_viz_dir / 'phase93_category_sunburst.html')
    print(f'  ✓ Saved: phase93_category_sunburst.html')
    fig_sunburst.show()

# ============================================================================
# Export Feature Category Summary
# ============================================================================
feature_viz_summary = {
    'timestamp': pd.Timestamp.now().isoformat(),
    'total_categories': len(PHASE93_FEATURE_CATEGORIES),
    'total_features_registered': sum(len(f) for f in PHASE93_FEATURE_CATEGORIES.values()),
    'total_features_present': total_phase93_features,
    'overall_coverage_pct': float(total_phase93_features / total_expected * 100),
    'visualizations_generated': [
        'phase93_feature_treemap.html',
        'phase93_category_coverage.html',
        'phase93_category_sector_heatmap.html',
        'phase93_feature_radar.html',
        'phase93_category_sunburst.html',
    ],
    'output_directory': str(feature_viz_dir),
    'category_summary': coverage_df.to_dict(orient='records'),
}

summary_path = feature_viz_dir / 'phase93_feature_viz_summary.json'
with open(summary_path, 'w') as f:
    json.dump(feature_viz_summary, f, indent=2)
print(f'\n✓ Summary saved: {summary_path}')

print(f'\n✓ Phase 9.3 Feature Category Visualizations Complete')
print(f'  Output directory: {feature_viz_dir}')
print(f'  HTML files: 5 visualizations generated')
print(f'  Categories visualized: {len(PHASE93_FEATURE_CATEGORIES)}')
print(f'  Features tracked: {total_expected} registered, {total_phase93_features} present')

================================================================================
PHASE 9.3 FEATURE CATEGORY VISUALIZATIONS
================================================================================

📊 Generating Feature Category Treemap...
  ✓ Saved: phase93_feature_treemap.html

📈 Generating Category Coverage Bar Chart...
  ✓ Saved: phase93_category_coverage.html

🔥 Generating Category-Sector Feature Heatmap...
  ✓ Saved: phase93_category_sector_heatmap.html

🎯 Generating Feature Completeness Radar Chart...
  ✓ Saved: phase93_feature_radar.html

🌐 Generating Category Distribution Sunburst...
  ✓ Saved: phase93_category_sunburst.html

✓ Summary saved: C:\Users\markm\PycharmProjects\Finance_ML_Analytics_Platform\outputs\eda\phase93_feature_categories\phase93_feature_viz_summary.json

✓ Phase 9.3 Feature Category Visualizations Complete
  Output directory: C:\Users\markm\PycharmProjects\Finance_ML_Analytics_Platform\outputs\eda\phase93_feature_categories
  HTML files: 5 visualizations generated
  Categories visualized: 21
  Features tracked: 295 registered, 232 present